import React, { useState, useMemo } from 'react';
import { 
  Ship, ShieldAlert, AlertTriangle, CheckCircle2, 
  Clock, Compass, ArrowRight, FileText, ChevronRight, BarChart3, Activity, Info,
  Sliders, ShieldCheck, Lock
} from 'lucide-react';
import { SpillIncident, PageId, VesselAttribution } from '../types';
import { useApp } from '../context/AppContext';

interface VesselAttributionPageProps {
  incident: SpillIncident;
  selectedVessel: VesselAttribution | null;
  onSelectVessel: (vessel: VesselAttribution | null) => void;
  onNavigate: (page: PageId) => void;
}

export const VesselAttributionPage: React.FC<VesselAttributionPageProps> = ({
  incident,
  selectedVessel,
  onSelectVessel,
  onNavigate,
}) => {
  const { isAdmin, classifiedIntel } = useApp();
  const vessels = incident?.vessels || [];
  const activeVessel = (selectedVessel && vessels.some(v => v.mmsi === selectedVessel.mmsi))
    ? selectedVessel
    : vessels[0];

  const classifiedForVessel = useMemo(() => {
    if (!activeVessel || !classifiedIntel) return [];
    const vesselName = (activeVessel.name || '').toLowerCase();
    const vesselMmsi = String(activeVessel.mmsi || '');

    return classifiedIntel.filter(item => {
      if (!item) return false;
      const flaggedMmsi = String(item.flaggedVesselMmsi || '');
      const summary = (item.summary || '').toLowerCase();
      const details = (item.details || '').toLowerCase();
      const title = (item.title || '').toLowerCase();

      return (
        (flaggedMmsi && flaggedMmsi === vesselMmsi) ||
        (vesselName && (summary.includes(vesselName) || details.includes(vesselName) || title.includes(vesselName))) ||
        (vesselMmsi && (summary.includes(vesselMmsi) || details.includes(vesselMmsi)))
      );
    });
  }, [activeVessel, classifiedIntel]);

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">
              Vessel Attribution & Forensic Correlation Engine
            </h1>
            <span className="px-2.5 py-0.5 rounded-full bg-blue-100 text-blue-800 text-xs font-bold font-mono">
              RANKING ENGINE
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Bayesian spatiotemporal intersection, trajectory matching, and behavioral anomaly heuristics ranking
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => onNavigate('reports')}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold transition-colors shadow-sm"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Generate Intelligence Report</span>
          </button>
        </div>
      </div>

      {/* CRITICAL LEGAL NOTICE / DISCLAIMER BANNER */}
      <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-xs text-amber-900 flex items-start gap-3 shadow-xs">
        <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h2 className="font-bold text-amber-950 text-xs uppercase tracking-wide">
            Attribution Notice & Legal Disclaimer
          </h2>
          <p className="leading-relaxed text-amber-900">
            The ranking scores and attribution percentages generated by this platform represent <strong>analytical spatiotemporal correlation and probabilistic suspicion</strong> derived from satellite SAR imagery, hydrodynamic reverse drift modeling, and commercial AIS transmission logs. <strong>They do NOT constitute definitive legal guilt, proof of violation, or judicial determination of culpability.</strong> Further on-site port state control inspections, oil fingerprinting, and fuel sample gas chromatography (GC-MS) are strictly required for legal enforcement.
          </p>
        </div>
      </div>

      {/* Main Grid: Left Ranked Suspect Cards / Table, Right Forensic Evidence Dossier */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Ranked Vessels List (7 cols) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <Ship className="w-4 h-4 text-blue-600" />
                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">
                  Suspected Vessels Correlation Hierarchy
                </h3>
              </div>
              <span className="text-xs font-mono text-slate-400">Total Analyzed: {vessels.length}</span>
            </div>

            {/* Ranked Suspects Cards */}
            <div className="space-y-3">
              {vessels.map((v) => {
                const isSelected = activeVessel.mmsi === v.mmsi;
                const isRank1 = v.rank === 1;

                return (
                  <div
                    key={v.mmsi}
                    onClick={() => onSelectVessel(v)}
                    className={`p-4 rounded-xl border transition-all cursor-pointer ${
                      isSelected 
                        ? 'bg-blue-50/70 border-blue-600 ring-2 ring-blue-600/20 shadow-md' 
                        : 'bg-slate-50/60 border-slate-200 hover:bg-slate-50 hover:border-blue-300'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div className="flex items-center gap-2.5">
                        <div className={`w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs font-mono ${
                          isRank1 ? 'bg-red-600 text-white' : 'bg-slate-800 text-slate-200'
                        }`}>
                          #{v.rank}
                        </div>
                        <div>
                          <div className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                            <span>{v.name}</span>
                            <span className="text-xs text-slate-400 font-normal">({v.flag})</span>
                          </div>
                          <div className="text-xs text-slate-500 font-mono">
                            MMSI: {v.mmsi} • IMO: {v.imo}
                          </div>
                        </div>
                      </div>

                      {/* Score Badge */}
                      <div className="text-right">
                        <span className={`px-2.5 py-1 rounded-lg font-mono font-extrabold text-sm ${
                          isRank1 
                            ? 'bg-red-100 text-red-700 border border-red-200' 
                            : v.overallScore >= 75 
                            ? 'bg-amber-100 text-amber-800 border border-amber-200' 
                            : 'bg-blue-100 text-blue-800'
                        }`}>
                          {v.overallScore}% SCORE
                        </span>
                        <span className="block text-[10px] text-slate-400 font-mono uppercase mt-0.5">
                          {v.confidence} Confidence
                        </span>
                      </div>
                    </div>

                    {/* Correlation Metrics Quick Strip */}
                    <div className="grid grid-cols-3 gap-2 py-2 border-t border-slate-200/60 text-xs font-mono">
                      <div>
                        <span className="text-slate-400 text-[10px] block font-sans">DISTANCE TO ORIGIN</span>
                        <span className="font-bold text-slate-800">{v.evidence.distanceAtOriginNM} NM</span>
                      </div>
                      <div>
                        <span className="text-slate-400 text-[10px] block font-sans">TIME COINCIDENCE</span>
                        <span className="font-bold text-slate-800">
                          {v.evidence.timeDifferenceMinutes > 0 ? `+${v.evidence.timeDifferenceMinutes}m` : `${v.evidence.timeDifferenceMinutes}m`}
                        </span>
                      </div>
                      <div>
                        <span className="text-slate-400 text-[10px] block font-sans">TRAJECTORY MATCH</span>
                        <span className="font-bold text-blue-600">{v.evidence.trajectoryMatchPercent}%</span>
                      </div>
                    </div>

                    {/* Primary Anomaly Flag Tag */}
                    {v.evidence.behaviorAnomalies.length > 0 && (
                      <div className="mt-2 text-xs text-amber-900 bg-amber-100/70 px-2.5 py-1.5 rounded-lg border border-amber-200 flex items-center gap-1.5">
                        <AlertTriangle className="w-3.5 h-3.5 text-amber-700 shrink-0" />
                        <span className="truncate">{v.evidence.behaviorAnomalies[0]}</span>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right Column: Selected Vessel Forensic Evidence Dossier (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-5">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <ShieldAlert className={`w-4 h-4 ${activeVessel.rank === 1 ? 'text-red-600' : 'text-blue-600'}`} />
                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">
                  Vessel Forensic Profile
                </h3>
              </div>
              <span className={`px-2 py-0.5 rounded font-mono text-xs font-bold ${
                activeVessel.rank === 1 ? 'bg-red-100 text-red-700' : 'bg-blue-100 text-blue-700'
              }`}>
                RANK #{activeVessel.rank}
              </span>
            </div>

            {/* Vessel particulars */}
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2 text-xs">
              <div className="flex items-center justify-between font-bold text-slate-900 text-sm">
                <span>{activeVessel.name}</span>
                <span className="font-mono text-xs text-slate-500">{activeVessel.type}</span>
              </div>
              <div className="grid grid-cols-2 gap-y-1.5 font-mono text-[11px] text-slate-600">
                <div><span className="text-slate-400">Flag:</span> {activeVessel.flag}</div>
                <div><span className="text-slate-400">Destination:</span> {activeVessel.destination}</div>
                <div><span className="text-slate-400">Dimensions:</span> {activeVessel.lengthM}m × {activeVessel.beamM}m</div>
                <div><span className="text-slate-400">Draught:</span> {activeVessel.draughtM}m</div>
              </div>
            </div>

            {/* Score Breakdown Bars */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                Correlation Component Scores
              </h4>

              <div className="space-y-2 text-xs">
                <div>
                  <div className="flex justify-between text-slate-600 mb-1">
                    <span>Spatial Proximity (0.8 NM to Origin)</span>
                    <span className="font-mono font-bold">{activeVessel.evidence.scoreBreakdown.spatialProximity}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-blue-600 rounded-full" style={{ width: `${activeVessel.evidence.scoreBreakdown.spatialProximity}%` }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-slate-600 mb-1">
                    <span>Temporal Alignment (-12 min delta)</span>
                    <span className="font-mono font-bold">{activeVessel.evidence.scoreBreakdown.temporalAlignment}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-blue-600 rounded-full" style={{ width: `${activeVessel.evidence.scoreBreakdown.temporalAlignment}%` }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-slate-600 mb-1">
                    <span>Trajectory Directional Correlation</span>
                    <span className="font-mono font-bold">{activeVessel.evidence.scoreBreakdown.trajectoryCorrelation}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-blue-600 rounded-full" style={{ width: `${activeVessel.evidence.scoreBreakdown.trajectoryCorrelation}%` }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-slate-600 mb-1">
                    <span>Behavioral Kinematic Penalty</span>
                    <span className="font-mono font-bold text-red-600">{activeVessel.evidence.scoreBreakdown.behavioralPenalty}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-red-500 rounded-full" style={{ width: `${activeVessel.evidence.scoreBreakdown.behavioralPenalty}%` }} />
                  </div>
                </div>
              </div>
            </div>

            {/* Behavioral Evidence Checklist */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                Forensic Behavioral Evidence
              </h4>
              <div className="space-y-1.5">
                {activeVessel.evidence.behaviorAnomalies.map((anom, idx) => (
                  <div key={idx} className="p-2 rounded-lg bg-red-50 border border-red-200 text-xs text-red-900 flex items-start gap-2">
                    <AlertTriangle className="w-3.5 h-3.5 text-red-600 shrink-0 mt-0.5" />
                    <span>{anom}</span>
                  </div>
                ))}

                <div className="p-2 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-700 flex items-start gap-2">
                  <Activity className="w-3.5 h-3.5 text-blue-600 shrink-0 mt-0.5" />
                  <span>
                    AIS Broadcast Status: <strong>{activeVessel.evidence.aisContinuity}</strong> during suspected discharge time window.
                  </span>
                </div>
              </div>
            </div>

            {/* Speed Profile Timeline Table */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                AIS Waypoint Speed History
              </h4>
              <div className="border border-slate-200 rounded-xl overflow-hidden text-xs font-mono">
                <table className="w-full text-left">
                  <thead className="bg-slate-50 border-b border-slate-200 text-[10px] text-slate-500">
                    <tr>
                      <th className="py-1.5 px-2.5">Time (UTC)</th>
                      <th className="py-1.5 px-2.5">Speed</th>
                      <th className="py-1.5 px-2.5">Course</th>
                      <th className="py-1.5 px-2.5">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {activeVessel.trackHistory.map((tr, i) => (
                      <tr key={i} className={tr.speedKnots < 5 ? 'bg-red-50/60 font-bold text-red-700' : 'text-slate-700'}>
                        <td className="py-1.5 px-2.5">{tr.timestamp}</td>
                        <td className="py-1.5 px-2.5">{tr.speedKnots} kts</td>
                        <td className="py-1.5 px-2.5">{tr.headingDeg}°</td>
                        <td className="py-1.5 px-2.5 text-[11px] truncate max-w-[120px]">{tr.navStatus}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Classified Defense Intercepts for this vessel (Admin Only) */}
            {isAdmin && classifiedForVessel.length > 0 && (
              <div className="p-3 rounded-xl bg-amber-950/40 border border-amber-500/40 space-y-2 text-xs font-mono">
                <div className="flex items-center gap-1.5 text-amber-400 font-bold">
                  <ShieldAlert className="w-3.5 h-3.5" />
                  <span>CLASSIFIED LAW ENFORCEMENT FLAG ATTACHED</span>
                </div>
                {classifiedForVessel.map(item => (
                  <div key={item.id} className="text-slate-300 text-[11px] bg-slate-900/90 p-2 rounded border border-amber-500/20">
                    <span className="text-amber-300 font-bold block">{item.title}</span>
                    <span className="text-slate-400">{item.summary}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Action buttons */}
            <div className="pt-2 space-y-2">
              <button
                onClick={() => onNavigate('reports')}
                className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs transition-colors shadow-sm"
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Export Vessel Dossier to Investigation Report</span>
              </button>

              {isAdmin ? (
                <button
                  onClick={() => onNavigate('admin')}
                  className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs transition-colors shadow-sm font-mono"
                >
                  <Sliders className="w-3.5 h-3.5" />
                  <span>Admin Recalibrate Scores & Weighting</span>
                </button>
              ) : (
                <div className="p-2 rounded-lg bg-slate-100 border border-slate-200 text-center text-[11px] text-slate-500 font-mono flex items-center justify-center gap-1.5">
                  <Lock className="w-3 h-3 text-slate-400" />
                  <span>Attribution weighting override restricted to Level 5 Admin</span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
